create: create book item card component
PutraHarianja/Skilvul-Kelompok11-TokoPinter pull request #10
Opened 2021-11-11 12:38 UTC by PutraHarianja

2021-11-11 13:37 UTC, josestg requested changes

2021-11-11 13:37 UTC, josestg commented on package.json
> +    "styled-component": "^2.8.0",
@PutraHarianja boleh diremove dulu ya kak yang ini. Kalay uda dicommit baru push lagi ke branch ini

2021-11-11 13:37 UTC, josestg commented on src/component/styled/book-item-card-styled.jsx
> +    font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
@PutraHarianja font-family nya berulang ulang, coba di caritau bagaimana cara biar bisa débuta global font-family nya.

2021-11-12 09:14 UTC, PutraHarianja commented on package.json
> +    "styled-component": "^2.8.0",
Solve. Sudah dihapus dari package.json

2021-11-12 09:14 UTC, PutraHarianja commented on src/component/styled/book-item-card-styled.jsx
> +    font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
Sudah bang, melakukan Extending Styles

2021-11-15 12:05 UTC, merged